<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\AN.Veldrid.Build.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Veldrid.LifetimeTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Veldrid\Veldrid.csproj" />
  </ItemGroup>

</Project>