#!/usr/bin/env pwsh
# gen-version-file.ps1 — Generate AN.Veldrid.Version.generated.props from version.json + git
#
# Reads version.json (base version + buildNumberOffset) and git info,
# writes a static .props file that MSBuild imports for all projects.
# This file is gitignored — regenerate after clone or version bump.
#
# Usage:
#   ./cmd/gen-version-file.ps1

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$versionJsonPath = Join-Path $repoRoot "version.json"
$outputPropsPath = Join-Path $repoRoot "AN.Veldrid.Version.generated.props"

# Locate JsonPeek.exe from ArtificialNecessity.CodeAnalyzers package
$jsonPeekExePath = Join-Path $env:USERPROFILE ".nuget\packages\artificialnecessity.codeanalyzers\0.1.13\tools\net8.0\any\JsonPeek.exe"
if (-not (Test-Path $jsonPeekExePath)) {
    Write-Host "ERROR: JsonPeek.exe not found at $jsonPeekExePath" -ForegroundColor Red
    Write-Host "Run 'dotnet restore src\Veldrid.sln' first to ensure ArtificialNecessity.CodeAnalyzers is installed." -ForegroundColor Yellow
    exit 1
}

# Read version.json
$baseVersion = & $jsonPeekExePath $versionJsonPath version
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: Failed to read 'version' from $versionJsonPath" -ForegroundColor Red; exit 1 }

$buildNumberOffset = & $jsonPeekExePath $versionJsonPath buildNumberOffset
if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: Failed to read 'buildNumberOffset' from $versionJsonPath" -ForegroundColor Red; exit 1 }

$versionPrefix = "$baseVersion.$buildNumberOffset"

# Git info
$gitCommitHeight = (git -C $repoRoot rev-list --count HEAD).Trim()
$gitShortHash = (git -C $repoRoot rev-parse --short HEAD).Trim()

$informationalVersion = "$versionPrefix+$gitCommitHeight.g$gitShortHash"

# Write the .props file
$propsContent = @"
<!-- AUTO-GENERATED by cmd/gen-version-file.ps1 — do not edit manually -->
<!-- Regenerate: ./cmd/gen-version-file.ps1 -->
<Project>
  <PropertyGroup>
    <VersionPrefix>$versionPrefix</VersionPrefix>
    <Version>$versionPrefix</Version>
    <AssemblyVersion>$versionPrefix.0</AssemblyVersion>
    <FileVersion>$versionPrefix.0</FileVersion>
    <InformationalVersion>$informationalVersion</InformationalVersion>
    <GitCommitHeight>$gitCommitHeight</GitCommitHeight>
    <GitShortHash>$gitShortHash</GitShortHash>
  </PropertyGroup>
</Project>
"@

Set-Content -Path $outputPropsPath -Value $propsContent -Encoding UTF8
Write-Host "Generated $outputPropsPath" -ForegroundColor Green
Write-Host "  Version:              $versionPrefix" -ForegroundColor Cyan
Write-Host "  AssemblyVersion:      $versionPrefix.0" -ForegroundColor Cyan
Write-Host "  InformationalVersion: $informationalVersion" -ForegroundColor Cyan